plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
}

dependencies {
    minecraft("com.mojang:minecraft:${minecraft_version}")
    implementation("net.fabricmc:fabric-loader:${fabric_loader_version}")
    implementation("net.fabricmc.fabric-api:fabric-api:${fabric_version}")
}

loom {
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
            if (project.hasProperty('graphicsBackend')) {
                programArgs('--graphicsBackend', project.property('graphicsBackend').toString())
            }
            if (project.hasProperty('quickTestWorld')) {
                programArgs('--quickPlaySingleplayer', project.property('quickTestWorld').toString())
            }
        }
        server { server(); setConfigName('Fabric Server'); ideConfigGenerated(true); runDir('runs/server') }
    }
}
