# Project
version=26.2-v1.0.0
group=com.github.tacowasa059
java_version=25

# Common
minecraft_version=26.2
mod_name=Gaming Everything
mod_author=TACOWASA_059
mod_id=gamingeverything
license=MIT
credits=
description=Gives the world, entities, items, sky and HUD an animated RGB gaming look.
minecraft_version_range=[26.2,26.3)
neo_form_version=26.2-1

# Fabric
fabric_version=0.152.1+26.2
fabric_loader_version=0.19.3

# NeoForge
neoforge_version=26.2.0.88
neoforge_version_range=[26.2.0,)
neoforge_loader_version_range=[11,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
