buildscript {
    repositories {
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        mavenCentral()
    }
    dependencies {
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
    }
}

plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle'
    id 'multiloader-publish'
}

apply plugin: 'org.spongepowered.mixin'

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"
    config "${mod_id}.mixins.json"
}

minecraft {
    mappings channel: 'official', version: minecraft_version
    runs {
        client {
            workingDirectory project.file('run')
            mods {
                gamingeverything {
                    source sourceSets.main
                }
            }
        }
        server {
            workingDirectory project.file('run')
            args '--nogui'
            mods {
                gamingeverything {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    annotationProcessor('org.spongepowered:mixin:0.8.5-SNAPSHOT:processor')
}

jar {
    manifest.attributes(['MixinConfigs': "${mod_id}.mixins.json"])
}
