plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'multiloader-publish'
}

neoForge {
    version = neoforge_version
    runs {
        client {
            client()
            gameDirectory = file('run')
            if (project.hasProperty('graphicsBackend')) {
                programArgument('--graphicsBackend')
                programArgument(project.property('graphicsBackend').toString())
            }
            if (project.hasProperty('quickTestWorld')) {
                programArgument('--quickPlaySingleplayer')
                programArgument(project.property('quickTestWorld').toString())
            }
        }
    }
    mods {
        "${mod_id}" { sourceSet sourceSets.main }
    }
}

dependencies {
    compileOnly project(':common')
}
